name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - uses: actions/checkout@v5

      - name: Build APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer -v android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: V2RayTool_APK
          path: bin/*.apk